//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataStorage
{
    using System;
    using System.Collections.Generic;
    
    public partial class DojoMiembro
    {
        public int Id { get; set; }
        public int DojoId { get; set; }
        public int MiembroId { get; set; }
    
        public virtual Dojo Dojo { get; set; }
        public virtual Miembro Miembro { get; set; }
    }
}
