//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataStorage
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DojoApplicationEntities : DbContext
    {
        public DojoApplicationEntities()
            : base("name=DojoApplicationEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Dojo> Dojo { get; set; }
        public virtual DbSet<DojoMiembro> DojoMiembro { get; set; }
        public virtual DbSet<Puntaje> Puntaje { get; set; }
        public virtual DbSet<RetoMiembro> RetoMiembro { get; set; }
        public virtual DbSet<Miembro> Miembro { get; set; }
        public virtual DbSet<Reto> Reto { get; set; }
    }
}
