//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataStorage
{
    using System;
    using System.Collections.Generic;
    
    public partial class Puntaje
    {
        public int Id { get; set; }
        public int RetoMiembroId { get; set; }
        public Nullable<int> PuntajeReto { get; set; }
    
        public virtual RetoMiembro RetoMiembro { get; set; }
    }
}
