//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataStorage
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Reto()
        {
            this.RetoMiembro = new HashSet<RetoMiembro>();
        }
    
        public int Id { get; set; }
        public int DojoId { get; set; }
        public string Nombre { get; set; }
        public Nullable<int> DiasTiempoLimite { get; set; }
    
        public virtual Dojo Dojo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RetoMiembro> RetoMiembro { get; set; }
    }
}
